name: markeymap
description:
  Interactive crossplatform app to show how Ed Markey has represented and fought
  for Massachusetts

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg:
    git:
      url: https://github.com/feilfeilundfeil/flutter_svg.git
      ref: feature/web
  firebase_core: ^0.4.5
  built_path_annotations: ^0.1.0
  cupertino_icons: ^0.1.3
  video_player: ^0.10.5
  url_launcher: ^5.4.11
  url_launcher_web: ^0.1.0

  meta: any
  gsheets: ^0.2.4
  money2: ^1.4.0
  intl: ^0.16.1

dev_dependencies:
  build_runner: ^1.7.4
  built_path: ^0.1.0
  intl_translation: ^0.17.10
  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: ^0.39.4
  build: ^1.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/header.png
    - assets/logo.png
    - assets/intro_video.mp4
    - assets/texture.png
    - assets/credentials.json
    - assets/town_svgs/

  fonts:
    - family: Gotham Narrow
      fonts:
        - asset: assets/fonts/GothamNarrow-Black.otf
          weight: 800
        - asset: assets/fonts/GothamNarrow-BlackItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/GothamNarrow-Bold.otf
          weight: 700
        - asset: assets/fonts/GothamNarrow-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/GothamNarrow-Book.otf
          weight: 400
        - asset: assets/fonts/GothamNarrow-BookItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/GothamNarrow-Light.otf
          weight: 300
        - asset: assets/fonts/GothamNarrow-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/GothamNarrow-Medium.otf
          weight: 500
        - asset: assets/fonts/GothamNarrow-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/GothamNarrow-Thin.otf
          weight: 100
        - asset: assets/fonts/GothamNarrow-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/GothamNarrow-Ultra.otf
          weight: 900
        - asset: assets/fonts/GothamNarrow-UltraItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/GothamNarrow-XLight.otf
          weight: 200
        - asset: assets/fonts/GothamNarrow-XLightItalic.otf
          weight: 200
          style: italic
